### ISSUE TITLE
Use 'failure' instead of 'error-chain'?

### ISSUE THREAD

**Issue by tarcieri** [coreos/yubihsm-rs#1]
Have you considered using @withoutboats's `failure` crate instead of `error-chain`?

https://github.com/withoutboats/failure

It's designed in a way which I think people were hoping error-chain would evolve into: namely using a procedural macro rather than `macro_rules!` to define the error type. I personally find the `macro_rules!` error-chain uses to be rather gnarly.

If you're interested in switching but don't want to do the work I'd be happy to send a PR.

**Comment by csssuf** [comment]
The error handling in this crate as it is right now hasn't had much thought put into it, so I'm not particularly attached to it. I'd certainly be interested to see how  `failure` might improve things here, so a PR would definitely be welcome!
