### ISSUE TITLE
Support creating Domains from u8 ID number?

### ISSUE THREAD

**Issue by tarcieri** [coreos/yubihsm-rs#2]
As far as I can tell the only way you can make a `Domain` is `Domain::from(&str)`:

https://github.com/coreos/yubihsm-rs/blob/master/src/types.rs#L13

This seems a little weird to me... `u8` feels a lot more natural, since (AFAIK) they are simply 0-16.

Perhaps a `Domain::new(number: u8)` that actually validated the domain number is in range (either panicking or returning a `Result`) would be useful?

If you had that, the `From<&str>` impl for `Domain` could use it, and you'd get range checking there too.

**Comment by csssuf** [comment]
Yeah, that definitely makes sense. I'm honestly not sure why I included `From<&str> for Domain` and I am not a fan of how easily it could panic, so I'm just going to remove that impl altogether.

**Comment by tarcieri** [comment]
Sweet, thanks!
