### ISSUE TITLE
Wrapper for yh_util_get_pubkey()

### ISSUE THREAD

**Issue by tarcieri** [coreos/yubihsm-rs#3]
This API seems fairly essential to actually leverage signing, as it seems needed to obtain the public key that corresponds to a private key generated on-device:

```rust
pub fn yh_util_get_pubkey ( session : * mut yh_session , id : u16 , data : * mut u8 , datalen : * mut usize , algorithm : * mut yh_algorithm ) -> yh_rc
```

**Comment by csssuf** [comment]
Yeah, this seems like an important one. I'd like to avoid creating crate-specific structures for public key representations, so I'd like to reuse key structures from another crate if it's possible and reasonable.

**Comment by tarcieri** [comment]
To my knowledge there is no crate that fits the bill there besides the one where I'm trying to consume this crate:

https://github.com/tendermint/signatory

...and that will be constrained to Ed25519 and secp256k1 for the foreseeable future.

I'm sure @newpavlov will eventually get around to implementing signatures in https://github.com/RustCrypto but for the time being I'd suggest making something like:

```rust
pub struct PubKey {
    pub alg: Algorithm,
    pub bytes: Vec<u8>
}
```

**Comment by tarcieri** [comment]
Also I'd be interested in sending a PR for this as I need it... fairly soon.

**Comment by csssuf** [comment]
Hmm, unfortunately a struct like that is exactly what I was trying to avoid. The only other possibility I've been able to find is reusing types from rust-openssl, which is obviously its own can of worms.

**Comment by tarcieri** [comment]
Yeah, I'd definitely recommend avoiding that. I think https://github.com/RustCrypto will eventually be your best bet, but in the meantime if you provided a type like this, something like Signatory acting as a consumer of this crate can handle extracting an appropriate static signature type depending on the algorithm.
